version: "3.9"

services:
  web:
    build: .
    container_name: medicine-photo-ai-web
    ports:
      - "8000:80"
    environment:
      # Optional Google OAuth configuration
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
