version: "3.9"

services:
  web:
    build: .
    image: medicine-photo-ai-python-demo:latest
    container_name: medicine-photo-ai-web
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      # Optional Google OAuth configuration
      - SESSION_SECRET=dev-compose-secret
      - GOOGLE_CLIENT_ID=
      - GOOGLE_CLIENT_SECRET=
    volumes:
      - uploads:/app/uploads
    restart: unless-stopped

volumes:
  uploads:
    driver: local
